services:
 v1_web_staging:
   restart: unless-stopped
   container_name: mywebsite_v1_web_staging
   build:
     context: .
     dockerfile: Dockerfile.staging
   command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
   #volumes:
   #  - .:/ppms
   expose:
     - 8000
   networks:
     private:
   env_file:
     - ./.env


 nginx_staging:
   restart: unless-stopped
   container_name: mywebsite_v1_nginx_staging
   build:
     context: ./nginx
     dockerfile: Dockerfile.staging
   volumes:
     - ./nginx/nginx.staging.conf:/etc/nginx/conf.d/default.conf
     - ./certs:/certs
   ports:
     - "8071:80"
     - "8072:443"
   networks:
     private:
   depends_on:
     - v1_web_staging


#volumes:
# certs:


networks:
 private:
   driver: bridge
   name: mywebsite_v1_staging