services:
  
  db:
    image: postgres:16.3
    container_name: db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env



  web:
    build: .
    depends_on:
      - db
    command: python /myWebsite/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/myWebsite
    ports:
      - "8000:8000"
    env_file:
      - ./.env
