services:
  
  db:
    image: postgres:16.3
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=my_website_pre_prod_db
      - POSTGRES_USER=my_website_pre_prod_user
      - POSTGRES_PASSWORD=Milka417%


  web:
    build: .
    command: python /myWebsite/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/myWebsite
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.pre_prod
      - POSTGRES_DB=my_website_pre_prod_db
      - POSTGRES_USER=my_website_pre_prod_user
      - POSTGRES_PASSWORD=Milka417%
      - SECRET_KEY=django-insecure-88=cvf+q0nz1sj91-+z#pvsh45-&=siu0v47n(4xsw9n$ab9$p
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=195.238.122.125 lutoslaw [::1]
