upstream mywebsite_v1 {
    server v1_web_staging:8000;
}

server {
    listen 80;
    server_name 195.238.122.125;

    location / {
        proxy_pass http://web_staging:8000;
        client_max_body_size 100M;
    }
}

