upstream mywebsite_v1 {
    server v1_web_staging:8000;
}

server {
    server_name 195.238.122.125;
    listen 80;
    return 301 https://195.238.122.125$request_uri;
}

server {
    listen 443;
    server_name 195.238.122.125;

    ssl_certificate /certs/mywebsite_v1_staging-cert.crt;
    ssl_certificate_key /certs/mywebsite_v1_staging-cert.key;

    location / {
        proxy_pass http://v1_web_staging:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 100M;
    }
}

